name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때마다 실행
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --base-href="/custompaint_example_chrome/" # ⚠️ 꼭 레포이름으로 수정

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
